set -g mouse on
set -g mode-keys vi
set -g default-terminal "screen-256color"

# Change prefix to ','
set -g prefix , 
unbind C-b
bind , send-prefix

# Bind Space to insert a comma and a space as this makes typing more convenient
unbind Space 
bind Space send-keys ", "
bind \\ next-layout

# Rebind splitting to more convenient keys
bind v split-window -h
bind h split-window -v
unbind '"'
unbind '%'

# Bind Alt + Arrow keys to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Start indexing windows and panes at 1
set -g base-index 1
setw -g pane-base-index 1
