[general]
import = [
    "./themes/themes/argonaut.toml"
]

[window.padding]
x = 10
y = 10

[font]
size = 12.0

[font.normal]
family = "Cascadia Code"
style = "Regular"

[font.bold]
family = "Cascadia Code"
style = "Bold Extended"

[font.bold_italic]
family = "Cascadia Code"
style = "Bold Extended Italic"

[font.italic]
family = "Cascadia Code"
style = "Extended Italic"

[selection]
save_to_clipboard = true
