" Set leader key to Space
let mapleader = " "

" Project pickers
nnoremap <silent> <leader>f :ProjectFiles<CR>
nnoremap <silent> <leader>g :ProjectGrep<CR>

" Disable the built-in matchparen plugin as it causes annoying cursor behavior.
let g:loaded_matchparen = 1
let g:loaded_netrw = 1

" Hide entry for the right click menu (nvim only)
aunmenu PopUp.How-to\ disable\ mouse
aunmenu PopUp.-2-

" General settings
set encoding=utf-8 " Use UTF-8 encoding
set mouse=a " Enable mouse support in all modes
set autoread " Automatically reload files changed outside Vim
set belloff=all " Disable bell sound / flash
set backspace=indent,eol,start " Make backspace work more intuitively
set nobackup noswapfile " Do not create backup or swap files
" Avoid warning when switching away from an unsaved file
set hidden
set confirm

" Line numbers & display settings
set number " Show line numbers
" Underline only the active window's cursor line
augroup my_cursorline
  autocmd!
  autocmd WinEnter,BufEnter * setlocal cursorline
  autocmd WinLeave,BufLeave * setlocal nocursorline
augroup END
set scrolloff=2 " Keep at least 2 lines above/below cursor when scrolling

" Horizontal split separator: use the per-window statusline, filled with a dash.
" Keep filenames per-window in the statusline.
set laststatus=2
set statusline=---[\ %t%h%m%r\ ]%=
set fillchars+=stl:-,stlnc:-

" Search settings
set incsearch " Enable incremental search
set nohlsearch " Don't highlight search matches
set ignorecase " Ignore case unless search pattern contains uppercase
set smartcase " Enable smart case search
set path+=** " Enable recursive searching for filenames
set modelines=0 " Limit the number of lines checked for modelines

" Indentation & Tabs
set autoindent " Indent new lines the same as the previous line
set expandtab " Convert tabs to spaces
set tabstop=2 shiftwidth=2 softtabstop=2 " Use 2 spaces per tab
" Wrap the columns at 80 chars when using gq but not when typing
set textwidth=80
augroup my_format_options
 autocmd!
 autocmd FileType * setlocal formatoptions-=t formatoptions-=c formatoptions-=a formatoptions+=q
augroup END

" UI Enhancements
syntax on
set termguicolors
colorscheme mr

set nowrap " Disable visual line wrapping
set listchars=eol:↲,tab:▸·,trail:•,nbsp:⎵ " Display special characters for whitespace

" Clipboard
if system('uname -s') == "Darwin\n"
  set clipboard=unnamed
else
  set clipboard=unnamedplus
endif

" Wildmenu
set wildmenu " Enhance command-line completion
set wildmode=list:longest,full " Wildmode settings
