#+title: .emacs.d
#+property: header-args :tangle init.el
#+startup: overview

The goal of this configuration is to improve the look and feel of
Emacs by providing the following features, while relying as much as
possible on built-in functionalities.
** Features
+ /Easy to install and deploy to different OSs/
+ /Provide better defaults/
  + Emacs provides a lot of variables which can be configured. We will
    try to provide to find the best combination of settings in order
    to make the most out of what stock Emacs has to offer.
+ /Clean and minimalist UI/
  + Displaying only what is needed so as to avoid any distraction or
    visual clutter.
+ /Increased discoverability/
  + Since Emacs is a self-documenting editor, we make sure that we can
    get the most out of its documentation and built-in features, as
    well as features provided by packages.
+ /Use modal editing/
  + While Emacs default keybindings are great, I think that greater
    speed and efficiency can be achieved using modal editing,
    especially for text manipulation. Modal editing can also be seen
    as more ergonomic since it does not rely on modifier keys and thus
    put less strain of the user's hands. We will seek to apply modal
    editing consistently across all Emacs packages, without relying on
    =evil= but on =meow= which provides a more practical and
    lighweight approach to modal editing.
** Design philosophy
+ KISS
  + Leverage built-in functionality
  + Use as few packages as possible
