[window.padding]
x = 0
y = 0

[font]
size = 12.0

[font.normal]
family = "Iosevka Term"
style = "Semibold Extended"

[font.italic]
family = "Iosevka Term"
style = "Semibold Extended Italic"

[font.bold]
family = "Iosevka Term"
style = "Bold Extended"

[font.bold_italic]
family = "Iosevka Term"
style = "Bold Extended Italic"

[selection]
save_to_clipboard = true
