[window.padding]
x = 5
y = 5

[font]
size = 16.0

[font.normal]
family = "Iosevka Term"
style = "Extralight Extended"

[font.bold]
family = "Iosevka Term"
style = "Extrabold Extended"

[font.bold_italic]
family = "Iosevka Term"
style = "Bold Extended Italic"

[font.italic]
family = "Iosevka Term"
style = "Thin Extended Italic"

[selection]
save_to_clipboard = true
